### ISSUE TITLE
Doesn't work for LuaJIT

### ISSUE THREAD

**Issue by FractalU** [wqferr/functional#1]
There was an issue with the 'table.unpack' api. It wasn't available under LuaJIT or Lua 5.1. The unpack function was available instead. I already fixed it myself with a simple polyfill.

-- LuaJIT polyfill
if not table.unpack then
	table.unpack = unpack
end

**Comment by wqferr** [comment]
Oh wow, I haven't touched this in what, years now? Could you please make a pull request for this? Also sorry for the late reply, I haven't been active on GitHub in general.

I currently don't have a development environment setup so I can't properly test, but I'd love to help. You could probably add something like

`
-- LuaJIT polyfill
local unpack = unpack or table.unpack
`

to line 47, then replace calls to `table.unpack` with just `unpack`. IMO that'd be better than changing the `table` global.

Another caveat, though, is that I don't think init.lua is automatically loaded in 5.1 if I recall correctly... Regardless, if you could test it out a bit I'd really appreciate it!

**Comment by wqferr** [comment]
I just saw the luarocks page and remembered: this is exactly the kind of stuff I couldn't be bothered with 2 years ago so I just said "nope, Lua 5.2 or higher". Glad to see someone cleaning up after my mess! Also just saw your issue over at teal, it's a nice feeling not only someone having found this old project of mine, and actually trying to keep it up to date. Just wanted to say I'm grateful and here if you need help.

**Comment by wqferr** [comment]
Forgot I need to tag you so you actually get these by email, sorry!

@FractalU

**Comment by wqferr** [comment]
Should work for 5.1 and JIT now! If it doesn't, please comment here and I'll reopen the issue. Meanwhile, I'm off to help over at creating functional.d.tl!
