### ISSUE TITLE
'lambda' suggestion

### ISSUE THREAD

**Issue by wolfoops** [wqferr/functional#32]
Hi, evilbadmad from reddit.
> On string lambda, may consider a specific form that match more lambda calculus? eg.
> 
> **(parameter-list)=>lua-or-lambda-expression** instead of **lua-expression**
> 
> This allow not predefined variable name and making some functional handy, eg The currying function for 2 parameters function
> 
>     local function add2(a,b)return a+b end 
>     local curry2 = _lambda'(f)=>(x)=>(y)=>f(x,y)' 
>     print(curry2(add2)(1)(3)) -- 4 
> 
> Some memorization may help save some overhead too.

This my expandLambda function to transform before eval by loadstring/load
```
local function expandlambda(expr)
  local params, body = expr:match'^(%b())=>(.*)'
  if not params then return expr end
  return string.format('function %s return %s end', params, expandlambda(body))
end
```
bye~

**Comment by wqferr** [comment]
Do you believe it should replace the current way lambdas are defined, with implicit, fixed-name parameters? Your current code allows for both, but do you think that's a good idea?

**Comment by wolfoops** [comment]
eh, I think when we use the word 'lambda', there should be something 'lambda'-ish ;)

But, may be we can have both version.
I modified the expandlambda a bit with second return value a true if it start with a lambda form (also allow beginning spaces).
```
    local function expandlambda(expr)
      local params, body = expr:match'^%s*(%b())=>(.*)'
      if not params then return expr end
      return string.format('function %s return %s end', params, expandlambda(body)), true
    end
```
Then, we can have a flag to switch version, eg.
```
    function exports.lambda(expr, env)
      ....
      local expanded, is_primary_lambda = expandlambda(expr)
      if is_primary_lambda then
      .... -- handle lambda version
      else
      .... -- handle predefined variable name version
  
```

**Comment by wqferr** [comment]
New lambda syntax should be coming up soon in a new PR, just so you know. It's in a function called lambda2 just so it doesn't screw up the current tests I have set up, but I do intend on replacing the current syntax with this.

**Comment by wqferr** [comment]
I believe the pull request is in a presentable state, if you want to take a look. Again, all functions are suffixed with a 2 for now.

**Comment by wqferr** [comment]
Suggestion has been officially merged onto master, thank you for your input!
