### ISSUE TITLE
actually, changing to git+https:// from git:// is more correcct

### ISSUE THREAD

**Issue by FractalU** [wqferr/functional#38]
I stumbled across a commit from luafilesystem. See https://github.com/lunarmodules/luafilesystem/commit/211c2a5d897db328a7776ddc11111a2051d5b7f3. The luarocks maintainer decided to switch to `git+https://` from `git://`, so that it ensures that fetching git repos from GitHub always works. For the `functional` repo case, the `git://` worked as well so far. But changing to `git+https://` ensures that it always works. Sorry for the inconvenience with another issue, but I didn't know this previously.

The rockspec version can just be `1.6.0-2`.

**Comment by FractalU** [comment]
Ah, I see that LuaRocks automatically converts `git://` to `git+htps://` for GitHub URLs. The proof is in this code snippet at https://github.com/luarocks/luarocks/blob/master/src/luarocks/fetch.tl#L576C1-L582C7. So, nothing needs to be changed. Therefore, this issue can be closed.

Sorry for the false alarm.

**Comment by wqferr** [comment]
Gonna be honest, I saw this issue the day it was created then completely forgot to check back in on it. If that happens again, feel free to ping me.
