### ISSUE TITLE
Rename from_iterated_call to just from

### ISSUE THREAD

**Issue by wqferr** [wqferr/functional#9]

**Comment by FractalU** [comment]
Hello wqferr
I presented my version of functional.d.tl in the teal issue.
https://github.com/teal-language/tl/issues/468

I had problems with declaring types for from_coroutine, from_iterated_call, compose, bind and bind_self.
Especially with compose things get more complicated with multiple return values of lua.
A lot of my work came from penlight. It's definitely worth checking out its .d.tl declarations.
Penlight also had delaration for functional programming along with a whole bunch of other definitions. It contains copy paste declaration to cover even more complicated cases. Might be considering copy paste declaration for 'functional.d.tl' as well.

Here is an example of valid lua program that is really hard to declare types in teal. It should point out problems of compose function with multiple return values of lua.

function f(x, y)
	return x + y
end

function g(x)
	return x, x + 1
end

function compose(f1, f2)
	return function(x) return f1(f2(x)) end
end

local h = compose(f, g)

print(h(5))

**Comment by wqferr** [comment]
Yeah, these problems requiring copy paste would be really easy to solve if https://github.com/teal-language/tl/pull/449 were stable, but it looks like it's going to take some time to make it into a release.

In the meantime, we have some options:

1. Just ignore it. Teal will be more strict with things by design, and if someone needs a functionality Teal doesn't support yet, they need to go to pure Lua;
2. Copy-solution. This would work, assuming we copy paste enough variations, but even then it's exponential. Besides that, the whole Iterator<T> record might need to be copy pasted in some cases, which would lead to even further copy pasting of things taking it any variation of Iterator.

Currently I'm tending more towards 1: annotate the simple cases, allow *some* use of complex cases with casts. This is what I'm currently doing in the PR (specifically with the from and from_packed functions).

However, if the copy paste problems aren't that severe (as with copying the whole module record thing, I don't know if that would really be necessary), then I think it would be good to increase the feature coverage for Teal.

**Comment by wqferr** [comment]
I think I'll keep it as is for now, just because copy-pasting does seem to require doing so with the whole Iterator<T>. When variadic type arguments become stable, this is the first thing I'll change. If you have anything more to add, though, feel free to reopen discussion here. It's just that I feel like it's alright as it is right now and there are more features I'd rather get working on.
